### ISSUE TITLE
cargo-hack-install: sporadic installation failures

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/actions#11]
This seems to be happening fairly frequently:

https://github.com/RustCrypto/formats/runs/5542244602

```
Run export URL=$(curl -s https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | \
jq: error (at <stdin>:1): Cannot iterate over null (null)
wget: missing URL
Usage: wget [OPTION]... [URL]...
```

**Comment by newpavlov** [comment]
Hm, weird. I don't remember having such issues previously. Maybe it's a temporary GitHub issue?

If the issue persists, I think we could cache the relevant binaries in this repository instead of retrieving it from relevant source repositories.

**Comment by tarcieri** [comment]
It's occurred several times in the past few weeks (unfortunately it's a bit hard to find the workflow runs in the history, since re-running them marks them as succeeded)

**Comment by newpavlov** [comment]
I think we can close this issue. Feel free to reopen it back if the issue persists.

**Comment by tarcieri** [comment]
It's still sporadically failing even with the retries:

- https://github.com/RustCrypto/block-ciphers/runs/5629602572?check_suite_focus=true
- https://github.com/RustCrypto/block-ciphers/runs/5629602557?check_suite_focus=true

**Comment by newpavlov** [comment]
I've added verbose flag to `curl`. Can you link next failure? Hopefully, we will get some useful info from it.

**Comment by tarcieri** [comment]
I came across this which might be helpful: https://github.com/taiki-e/install-action

It supports both `cargo-hack` and `cross` among other things.

**Comment by newpavlov** [comment]
It looks like it uses fixed versions, which get updated from time to time. We could easily switch to such approach ourselves without relying on a third-party action (which IIUC also pulls Node for some reason).

**Comment by tarcieri** [comment]
Happened again: https://github.com/RustCrypto/formats/runs/5633623809?check_suite_focus=true

Seems to be returning a 403

**Comment by newpavlov** [comment]
It looks like by default curl does not retry on 40x errors. We need to add the `--fail` flag for that.

**Comment by tarcieri** [comment]
Failed again even with `--fail`:

https://github.com/RustCrypto/formats/runs/5696525279?check_suite_focus=true

```
Run export URL=$(curl --retry 10 --fail -s https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | \
  export URL=$(curl --retry 10 --fail -s https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | \
    jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
  wget -O /tmp/binaries.tar.gz $URL
  tar -C /tmp -xzf /tmp/binaries.tar.gz
  mv /tmp/cargo-hack ~/.cargo/bin
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CARGO_INCREMENTAL: 0
    RUSTFLAGS: -Dwarnings
wget: missing URL
```

Maybe it could just have a fallback URL for when this happens?

**Comment by newpavlov** [comment]
Nah, I think I will simply commit binaries into this repo. Hopefully, we will not have the same issue with direct raw.githubusercontent.com links.

**Comment by tarcieri** [comment]
It seems like it's the API that's having sporadic failures/possible rate limiting, and you could just hardcode a URL rather than putting binaries in this repo? That makes the audit trail harder.
