### ISSUE TITLE
Replacement for `actions-rs/toolchain`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/actions#17]
We use this action all over our CI configs, but it seems to be unmaintained: https://github.com/actions-rs/toolchain/issues/216

However, it seems like what we need could be a *dramatically simpler*. The runners already have `rustup` installed, so we just need to run something like the following:

```
$ rustup toolchain install --profile minimal --no-self-update ${{ toolchain }}
$ rustup default ${{ toolchain }}
```

**Comment by pinkforest** [comment]
You'll need to cache it too and keep track of it.. you could write several steps and hope for the best or just use via one step

e.g. I've cached zig and I set the cache key based on GH runner OS/Arch : https://github.com/rinse-repeat/zig-gh-helper

But on the case of toolchain you would need to cache it via target e.g. it's toolchain and it's better if you can cache the toolchain separately from the main action in matrix as GitHub actions have tendency to get stuck waiting randomly

Unless ofcourse you cache all the toolchains in the world you might need and then pull one big general cache and then just pull that one cache that is right / fit for the project in every matrix task repeatedly... may sound wasteful depending on who you ask

**Comment by tarcieri** [comment]
If we call `rustup` directly it will use binary release channels.

Caching would be nice but would probably be best handled by a caching-specific action like [`rust-cache`](https://github.com/Swatinem/rust-cache)

**Comment by tarcieri** [comment]
It looks like @dtolnay has a maintained action for this: https://github.com/dtolnay/rust-toolchain

**Comment by pinkforest** [comment]
Yeah looks useful
