### ISSUE TITLE
Preserve crates.io index?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/actions#2]
Right now each of our CI job spends 40-50 seconds updating crates.io index from scratch. It would be nice to use an already updated index across jobs, at very least inside one workflow.

cc @aewag

**Comment by aewag** [comment]
We could use GithubActions Cache for this. In a test job 
[a crates.io index update with cache](https://github.com/aewag/hashes/runs/5265187433?check_suite_focus=true#step:5:1) takes ca. 4 s (incl. the overhead to access the cache) 
in comparison [a crates.io index update w/o cache](https://github.com/aewag/hashes/runs/5265187476?check_suite_focus=true#step:4:1) runs for 54 s.

I would suggest to use a composite action for this. I'll just created #10.

**Comment by aewag** [comment]
@newpavlov The cache key now consists of the runner OS and the rust version. I just tested the cache use within https://github.com/RustCrypto/hashes/pull/369. This works as expected. No job has to again update its crates.io index, which saves time.

PR https://github.com/RustCrypto/actions/pull/10 is ready for review. After it is merged I'll change https://github.com/RustCrypto/hashes/pull/369 to point to the RustCrypto/actions repo.

**Comment by newpavlov** [comment]
Closed in #10
