### ISSUE TITLE
Fail fast for minimal-versions check

### ISSUE THREAD

**Issue by joshka** [RustCrypto/actions#40]
In https://github.com/RustCrypto/elliptic-curves/pull/1039#issuecomment-2030154457 we noted that the use of hack to test combinations can be overkill (and take a long time when there are lots of combinations - some combinations were as long as 15-30 minutes).

As an optimization, perhaps adding `cargo test --all-features` as an initial step to the workflow would be the right thing to do. If that fails, there there's enough information to get started on fixing the problem and running cargo-hack won't be all that helpful.

**Comment by newpavlov** [comment]
Note that you already can overwrite the default command by providing the [`stable-cmd`](https://github.com/RustCrypto/actions/blob/master/.github/workflows/minimal-versions.yml#L28-L30)  variable.

**Comment by joshka** [comment]
Good idea to push this upstream!

**Comment by newpavlov** [comment]
This will be [fixed](https://github.com/taiki-e/cargo-hack/pull/247) by `cargo hack` in a future release.
